### ISSUE TITLE
Possible implementation error in normalizations(int nObject) in BipartiteMatching

### ISSUE THREAD

**Issue by weininghu1012** [alexandrebouchard/blangGradAssignment-scaffold#1]
Hi Professor, 
In the below line of code, in our understanding, it should be doing normalization for all possible combination of the graph with different sizes on each side and should be square of C(n,k). Thus in the below line of code, we think it should be:
result.set(size, 2.0 * logFactorial(nObject) - **2.0***logFactorial(size) - 2.0 * logFactorial(nObject - size))

You might miss a 2 here.

https://github.com/alexandrebouchard/blangGradAssignment-scaffold/blob/7e3e26a5965bd9fed436a0a08355afeadf737818/src/main/java/matchings/BipartiteMatching.xtend#L72

Correct us if anything is missing. Thank you!

**Comment by weininghu1012** [comment]
Oh no worry, we got it solved.

**Comment by alexandrebouchard** [comment]
I confirm the 2 was intentionally not included. This comes out of some combinatorics calculation that I can go over during the next office hour.
